// Regenerate src/app/basemap.ts — the country outlines the place map draws on.
//
// Run: node scripts/make-basemap.mjs
//
// Why a vendored, generated file rather than a fetch: MCP App resources render
// under a deny-by-default CSP, so the map cannot request tiles or a GeoJSON at
// runtime. The geometry has to be IN the bundle, which means it has to be small
// — hence the aggressive simplification below, not just a copy of the source.
//
// Source: Natural Earth 1:110m Admin 0 countries, public domain (CC0), via
// github.com/nvkelso/natural-earth-vector. No attribution is legally required;
// the credit below ships anyway because the map should say where its coastline
// came from.
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const SOURCE =
  "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson";

/** The six IWAC countries — drawn filled, and clickable. */
const IWAC = ["Benin", "Burkina Faso", "Côte d'Ivoire", "Niger", "Nigeria", "Togo"];

/**
 * Neighbours drawn as a faint outline only. Without them the six countries
 * float in empty space and the map is unreadable as geography; with the whole
 * continent it stops fitting. This is the smallest set that reads as West
 * Africa.
 */
const CONTEXT = ["Ghana", "Mali", "Guinea", "Senegal", "Cameroon", "Chad", "Liberia", "Sierra Leone", "Mauritania", "Guinea-Bissau", "Gambia", "Algeria", "Central African Rep."];

/** Perpendicular distance from p to the segment a-b, in degrees. */
function perpendicular(p, a, b) {
  const dx = b[0] - a[0];
  const dy = b[1] - a[1];
  if (dx === 0 && dy === 0) return Math.hypot(p[0] - a[0], p[1] - a[1]);
  const t = Math.max(0, Math.min(1, ((p[0] - a[0]) * dx + (p[1] - a[1]) * dy) / (dx * dx + dy * dy)));
  return Math.hypot(p[0] - (a[0] + t * dx), p[1] - (a[1] + t * dy));
}

/** Ramer-Douglas-Peucker. Tolerance is in degrees. */
function simplify(points, tolerance) {
  if (points.length < 3) return points;
  let worst = 0;
  let index = 0;
  for (let i = 1; i < points.length - 1; i++) {
    const d = perpendicular(points[i], points[0], points[points.length - 1]);
    if (d > worst) {
      worst = d;
      index = i;
    }
  }
  if (worst <= tolerance) return [points[0], points[points.length - 1]];
  return [
    ...simplify(points.slice(0, index + 1), tolerance).slice(0, -1),
    ...simplify(points.slice(index), tolerance),
  ];
}

// ~0.06° ≈ 6 km, which is a third of a pixel on a 900px map spanning 35° of
// longitude: below what any viewer can resolve, and it cuts the point count
// by roughly 4x.
const TOLERANCE = 0.06;
/** 2 decimals ≈ 1.1 km. Rounding is most of the byte saving. */
const round = (v) => Math.round(v * 100) / 100;

/** Drop rings that survive simplification as a sliver — offshore islands, mostly. */
function keepRing(ring) {
  if (ring.length < 4) return false;
  const lons = ring.map((p) => p[0]);
  const lats = ring.map((p) => p[1]);
  return Math.max(...lons) - Math.min(...lons) > 0.25 || Math.max(...lats) - Math.min(...lats) > 0.25;
}

function ringsOf(geometry) {
  const polys = geometry.type === "Polygon" ? [geometry.coordinates] : geometry.coordinates;
  return polys.flatMap((poly) => poly.slice(0, 1)); // outer ring only; holes are invisible at this scale
}

const response = await fetch(SOURCE);
if (!response.ok) throw new Error(`Natural Earth fetch failed: ${response.status}`);
const geo = await response.json();

const nameOf = (f) => f.properties.NAME ?? f.properties.ADMIN;
const wanted = new Set([...IWAC, ...CONTEXT]);
const features = geo.features.filter((f) => wanted.has(nameOf(f)));
const missing = [...wanted].filter((n) => !features.some((f) => nameOf(f) === n));
if (missing.length) console.warn(`  not found in the source (skipped): ${missing.join(", ")}`);

const countries = features
  .map((f) => ({
    name: nameOf(f),
    iwac: IWAC.includes(nameOf(f)),
    rings: ringsOf(f.geometry)
      .map((ring) => simplify(ring, TOLERANCE).map(([x, y]) => [round(x), round(y)]))
      .filter(keepRing),
  }))
  .filter((c) => c.rings.length)
  .sort((a, b) => Number(b.iwac) - Number(a.iwac) || a.name.localeCompare(b.name));

const all = countries.flatMap((c) => c.rings.flat());
const bounds = {
  west: round(Math.min(...all.map((p) => p[0])) - 0.5),
  east: round(Math.max(...all.map((p) => p[0])) + 0.5),
  south: round(Math.min(...all.map((p) => p[1])) - 0.5),
  north: round(Math.max(...all.map((p) => p[1])) + 0.5),
};
const points = all.length;

const body = `// GENERATED by scripts/make-basemap.mjs — do not edit by hand.
//
// Country outlines for the place map, simplified to ${points} points at
// ${TOLERANCE}° tolerance and 2-decimal precision (~1 km). MCP App resources
// render under a deny-by-default CSP, so no tile server and no runtime GeoJSON
// fetch is possible: the geometry has to ship inside the bundle, and therefore
// has to be small.
//
// Source: Natural Earth 1:110m Admin 0 countries (public domain / CC0),
// github.com/nvkelso/natural-earth-vector. Re-run the script to refresh.

export interface BasemapCountry {
  name: string;
  /** True for the six countries the collection covers; the rest are context. */
  iwac: boolean;
  /** Outer rings only — holes and islets are invisible at this scale. */
  rings: [number, number][][];
}

/** Lon/lat extent of the drawn geometry, with a half-degree margin. */
export const BASEMAP_BOUNDS = ${JSON.stringify(bounds)};

export const BASEMAP: BasemapCountry[] = ${JSON.stringify(countries)};
`;

const out = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "app", "basemap.ts");
writeFileSync(out, body);
console.log(
  `  basemap  ${countries.length} countries · ${points} points · ${(Buffer.byteLength(body) / 1024).toFixed(1)}kb -> src/app/basemap.ts`,
);
